# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    dao.utilisateur:
        class: Formation\CinemaCrud\MainBundle\DAO\UtilisateurDAO
        arguments: ["@database_connection"]
